ipynb-filters: [nbprocess_filter]

project:
  type: website
  output-dir: docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "test_fastscript"
  description: "foo"
  execute: 
    enabled: false
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-branch: main
  repo-url: https://github.com/hamelsmu/test_fastscript/tree/main/
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        file: index.ipynb
    right:
      - icon: github
        href: https://github.com/hamelsmu/test_fastscript/tree/main/
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml

