# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['test_fastscript_add']

# %% ../00_core.ipynb 3
from fastcore.script import call_parse

@call_parse
def test_fastscript_add(a:int, # first num to add
                        b:int # second num to add
                       ): 
    s = a + b
    print(s)
    return s
